### PR TITLE
Upgrade to symfony 4.3

### PR DESCRIPTION
**Pull request by loic425**

### CODE REVIEW

**Comment by lchrusciel** [comment]
We have some issues with Symfony 4.3 so I think it is not enough to just update dependencies. Some of these errors are described here: https://github.com/Sylius/Sylius/pull/10432

Loic, can we turn on Travis CI for this repo?

**Comment by loic425** [comment]
> We have some issues with Symfony 4.3 so I think it is not enough to just update dependencies. Some of these errors are described here: [Sylius/Sylius#10432](https://github.com/Sylius/Sylius/pull/10432)
> 
> Loic, can we turn on Travis CI for this repo?

I don't know why Travis CI build is not shown here, cause Travis is enabled for this project. I've seen the build errors:
https://travis-ci.org/Monofony/SymfonyStarter/builds/541207014

**Comment by loic425** [comment]
@lchrusciel Thanks to Sylius/Sylius#10432 notes I upgraded with symfony 4.3.1 and everything works 👍

**Comment by loic425** [comment]
@smildev @lchrusciel  This pull request has evolved. Some issues fixed by upgrading on Symfony 4.3.1 and by adding psr/event-dispatch on dev requirements as suggested by @mugslug on https://github.com/vimeo/psalm/issues/1752

**Pull request merged**
